### ISSUE TITLE
Google Services

### ISSUE THREAD

**Issue by brianoh** [krolmic/recipes_app#23]
First: google-services.json missing. Found one and installed it.
Second: when running "flutter run":
"FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.company.recipes'"

**Comment by twuh** [comment]
Have you download the google-services.json from your firebase ?

**Comment by brianoh** [comment]
First: google-services.json missing. Found one and installed it.

Second: when running "flutter run":
"FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':app:processDebugGoogleServices'.

Have you tried downloading and running it?

**Comment by brianoh** [comment]
I registered with FireBase and created FireStore collection - I think as described. I installed the google-services.json file as described and made other edits as described on FireBase. I now get the following error: (Any ideas?).
```
To quit, press "q".
E/flutter (30419): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
E/flutter (30419): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
E/flutter (30419): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302)
E/flutter (30419): <asynchronous suspension>
E/flutter (30419): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:226)
E/flutter (30419): <asynchronous suspension>
E/flutter (30419): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:281)
E/flutter (30419): #4      _rootRun (dart:async/zone.dart:1120)
E/flutter (30419): #5      _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (30419): #6      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150)
E/flutter (30419): #7      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609)
E/flutter (30419): #8      Future._propagateToListeners (dart:async/future_impl.dart:665)
E/flutter (30419): #9      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348)
E/flutter (30419): #10     _rootRun (dart:async/zone.dart:1124)
E/flutter (30419): #11     _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (30419): #12     _CustomZone.runGuarded (dart:async/zone.dart:923)
E/flutter (30419): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
E/flutter (30419): #14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (30419): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
E/flutter (30419):
```

**Comment by krolmic** [comment]
Hi brianoh,

did you already try with [this approach](https://github.com/flutter/flutter/issues/25640#issuecomment-449589417)?

I'll close this issue, for now, please open a new issue if the error still occurs.
